# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-13 17:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('street', models.CharField(max_length=90)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=90)),
                ('pre_tax_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('categories', models.ManyToManyField(to='upload_app.Category')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload_app.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload_app.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='TaxName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ZipCode',
            fields=[
                ('zipcode', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='expense',
            name='tax_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload_app.TaxName'),
        ),
        migrations.AddField(
            model_name='employee',
            name='zipcode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload_app.ZipCode'),
        ),
        migrations.AlterUniqueTogether(
            name='expense',
            unique_together=set([('date', 'description', 'pre_tax_amount', 'employee')]),
        ),
        migrations.AlterUniqueTogether(
            name='employee',
            unique_together=set([('first_name', 'last_name', 'street')]),
        ),
    ]
